### ISSUE TITLE
hello，我最近也在做OSM立交桥的识别，请你你这个思路最后做的怎么样

### ISSUE THREAD

**Issue by yangpei11** [BranZhang/intersection-3d-rebuild#1]

**Comment by BranZhang** [comment]
你仅仅是做立交桥的识别吗？我这个是尝试把立交桥的z轴上的高度计算出来。

**Comment by yangpei11** [comment]
还没到那一步，现在OSM数据只有二维平面信息，不知道如何变成3维OSM，我是北京大学的硕士能加下微信讨论下吗？YangpeiPku

------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"BranZhang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月27日(星期五) 晚上6:25
收件人:&nbsp;"BranZhang/intersection-3d-rebuild"<intersection-3d-rebuild@noreply.github.com&gt;;
抄送:&nbsp;"杨沛"<522338631@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [BranZhang/intersection-3d-rebuild] hello，我最近也在做OSM立交桥的识别，请你你这个思路最后做的怎么样 (#1)




你仅仅是做立交桥的识别吗？我这个是尝试把立交桥的z轴上的高度计算出来。
